slf4j-api update
jmdns/jmdns pull request #256
Opened 2023-08-10 09:39 UTC by usnasoft

updated slf4j-api version from  1.7.36 to 2.0.7
updated <jvm.version> to 1.8

modified all lines like:
private static Logger   logger = LoggerFactory.getLogger(Xxx.class.getName);
into:
private static Logger   logger = LoggerFactory.getLogger(Xxx.class);

removed String concatenations in log messages

2023-08-13 21:00 UTC, kaikreuzer requested changes
Many thanks for these updates!
Please find a few small comments below.

2023-08-14 07:27 UTC, usnasoft commented on .classpath
> -<?xml version="1.0" encoding="UTF-8"?>
I edited it; as you know this file is managed by eclipse, it ptobably depends on IDE version; hopefully it will not change again

2023-08-14 07:36 UTC, usnasoft commented on pom.xml
> +			<!-- version>1.7.36</version -->
done; I should delete the line before commit

2023-08-14 07:37 UTC, usnasoft commented on src/main/java/javax/jmdns/impl/DNSRecord.java
> +//        private static Logger logger1 = LoggerFactory.getLogger(Address.class);
done; I should had delete the line before push

2023-08-14 07:46 UTC, usnasoft commented
many thanks to you; this library is by far the best mDNS implementation I was able to find

2023-08-14 09:09 UTC, kaikreuzer commented on .classpath
> -<?xml version="1.0" encoding="UTF-8"?>
It still appears as completely changed. Maybe you need to re-commit it after having it removed from the .gitignore file?

2023-08-14 09:55 UTC, closed without merging

2023-08-15 09:02 UTC, usnasoft commented
Closed and reopened as new request to simplify merge