Fix #212: Cleanup and modernize Browser sample
jmdns/jmdns pull request #309
Opened 2024-09-29 14:38 UTC by melloware

Fix #212: Cleanup and modernize Browser sample

![image](https://github.com/user-attachments/assets/cd576b70-7e39-4d9e-adb1-6954c40971fb)

2024-10-08 06:44 UTC, janossch requested changes

2024-10-08 06:44 UTC, janossch commented on src/sample/java/com/strangeberry/jmdns/tools/Browser.java
> +    static MdnsBrowser instance;
I think this should be `Browser`

```suggestion
    static Browser instance;
```

2024-10-08 06:44 UTC, janossch commented on src/sample/java/com/strangeberry/jmdns/tools/Browser.java
> -        System.out.println("ADD: " + name);
Maybe it is just my personal preference to like reading logs but what I suggest is to create a private method where you do the logging. By default it is switched off and if someone who feels the irresistible need could switch it back on.

2024-10-08 06:44 UTC, janossch commented on src/sample/java/com/strangeberry/jmdns/tools/Browser.java
> +import java.io.Serial;
`java.io.Serial` is this really used?
```suggestion
```

2024-10-08 13:14 UTC, janossch approved these changes
Looks good to me!

2024-10-10 19:15 UTC, kaikreuzer commented on src/sample/java/samples/Browser.java
> +package javax.jmdns.tools;
But now there is no license header at all...?

2024-10-10 19:17 UTC, kaikreuzer commented
It would be nice if you could keep the code history in place by doing two separate commits: One merely moving the file to the new location (git can than track it and associate the old and new location) and one with the code changes.

2024-10-10 19:19 UTC, melloware commented
Yep fixing the headers now

2024-10-10 19:20 UTC, melloware commented
Weird i moved them all the same in IntelliJ its funny two were moves and one was an Add and Delete?

2024-10-10 19:36 UTC, melloware commented
OK from what I understand this is Git default behavior

2024-10-10 19:36 UTC, closed without merging